typedef enum
{
    LEA, IMM, JMP, CALL, JZ, JNZ, ENT, ADJ, LEV, RET, LI, LC, SI, SC, SET, GET, PUSH, GETELEM, SETELEM, ADDELEM,
    OR, XOR, AND, EQ, NE, LT, GT, LE, GE, ADD, SUB, MUL, DIV, MATMUL, POS, NEG, NOT, SHL, SHR,
    OPEN, READ, CLOSE, PRTF, MALC, MSET, MCMP, EXIT
} VM_INSTRUCTION;

extern void* any_value;
